#! /bin/sh

#xrandr --rate 144
sxhkd &
setxkbmap -layout us,ru,am -variant ,,phonetic -option grp:alt_shift_toggle
$HOME/.config/polybar/launch.sh
xsetroot -cursor_name left_ptr
bspc monitor -d I II III IV V VI VII VIII IX X
gap=15
PANEL_HEIGHT=27
export gap
export PANEL_HEIGHT

bspc config window_gap $gap
bspc config top_padding $(($PANEL_HEIGHT-$gap))
#bspc config top_padding 0
bspc config left_padding -$gap
bspc config right_padding -$gap
bspc config bottom_padding -$gap
bspc config border_width         1
bspc config automatic_scheme alternate

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config paddingless_monocle false 

bspc config focused_border_color "#1ABB9B"
bspc config normal_border_color "#222D32"
bspc config presel_feedback_color "#1ABB9B"

bspc config focus_follows_pointer true
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
#bspc rule -a cemu.exe state=pseudo_tiled
bspc config external_rules_command ~/.config/bspwm/scripts/external_rules.sh
# For java application, Intellij to be specific
wmname LG3D
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
